import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
)

const challenges = [
  // --- STONE (débutant) ---
  {
    leagueName: '7ajra',
    title: 'Refonte homepage SaaS',
    brief: 'Redesigne la page d\'accueil d\'un SaaS B2B fictif pour améliorer la conversion.',
    context: 'StartupPay est une fintech qui propose des paiements en ligne pour PME. Leur homepage actuelle convertit à 1,2% et souffre d\'un manque de clarté sur la proposition de valeur.',
    deliverable: 'Maquette haute-fidélité de la homepage (desktop uniquement). Export PNG + fichier source (Figma ou XD).',
    constraints: '- Utiliser une palette de 2 couleurs maximum\n- Section hero avec CTA clair\n- Pas d\'animations\n- Respecter les règles d\'accessibilité WCAG AA',
    criteria: '- Clarté du message principal\n- Hiérarchie visuelle\n- Qualité du CTA\n- Cohérence graphique',
    specialty: 'UI Designer',
    challenge_type: 'Redesign',
    industry: 'Fintech',
    track: 'ux_ui',
    xp_reward: 150,
    deadline_days: 7,
  },
  {
    leagueName: '7ajra',
    title: 'Logo minimaliste e-commerce',
    brief: 'Crée le logo d\'une boutique en ligne de mode éthique pour une audience millennial.',
    context: 'Slowear est une marque de vêtements éco-responsables lancée par une jeune entrepreneuse. Elle cherche un logo épuré qui reflète durabilité et modernité.',
    deliverable: 'Logo vectoriel (SVG + PDF) en version principale et monochrome. Présentation sur fond clair et foncé.',
    constraints: '- Typographie uniquement (aucune icône)\n- Max 2 couleurs\n- Lisible en 24px et en grand format\n- Livrer les sources en format vectoriel',
    criteria: '- Originalité et mémorabilité\n- Adéquation avec la marque\n- Polyvalence sur différents fonds\n- Qualité des courbes vectorielles',
    specialty: 'Graphic Designer',
    challenge_type: 'Logo',
    industry: 'Mode',
    track: 'graphic',
    xp_reward: 150,
    deadline_days: 5,
  },
  {
    leagueName: '7ajra',
    title: 'User flow onboarding app mobile',
    brief: 'Cartographie le parcours d\'inscription d\'un utilisateur sur une app de nutrition.',
    context: 'NutriSnap est une app mobile qui génère des plans alimentaires personnalisés. Le taux de complétion de l\'onboarding est de 34%, bien en dessous de la moyenne du secteur.',
    deliverable: 'Diagramme de flux (user flow) couvrant toutes les étapes de l\'onboarding, du premier lancement jusqu\'au tableau de bord. Annoté avec les décisions et états d\'erreur.',
    constraints: '- Utiliser des formes standardisées (cercle = début/fin, rectangle = étape, losange = décision)\n- Inclure les chemins d\'erreur\n- Max 20 nœuds\n- Livrable en PNG ou PDF',
    criteria: '- Exhaustivité du parcours\n- Lisibilité et organisation\n- Prise en compte des cas d\'erreur\n- Clarté des annotations',
    specialty: 'UX Designer',
    challenge_type: 'User Flow',
    industry: 'Nutrition',
    track: 'ux_ui',
    xp_reward: 150,
    deadline_days: 5,
  },
  {
    leagueName: '7ajra',
    title: 'Affiche événement musical',
    brief: 'Conçois l\'affiche d\'un festival de musique électronique underground parisien.',
    context: 'VOID est un collectif parisien qui organise des soirées techno dans des lieux atypiques. Leur prochaine édition se tient le 15 juin dans une ancienne usine à Saint-Denis.',
    deliverable: 'Affiche format A3 (300dpi) prête à l\'impression. Export haute résolution JPG/PDF.',
    constraints: '- Fond sombre obligatoire\n- Inclure : nom de l\'événement, date, lieu, 3 artistes\n- Typographie impactante\n- Pas de photos réelles de personnes',
    criteria: '- Impact visuel immédiat\n- Lisibilité de l\'information essentielle\n- Cohérence avec l\'univers musical\n- Qualité d\'impression (résolution, marges)',
    specialty: 'Graphic Designer',
    challenge_type: 'Affiche',
    industry: 'Musique',
    track: 'graphic',
    xp_reward: 150,
    deadline_days: 5,
  },

  // --- BRONZE ---
  {
    leagueName: 'Bronze',
    title: 'Design system couleurs & typo',
    brief: 'Construis la base d\'un design system pour une app de gestion de projets SaaS.',
    context: 'Taskly est un SaaS de gestion de tâches en croissance rapide. Leur équipe de 3 designers travaille sans référentiel commun, causant incohérences visuelles et ralentissant les sprints.',
    deliverable: 'Fichier Figma structuré avec : palette de couleurs sémantiques, scale typographique, tokens de base (spacing, radius, shadow). Documentation dans le fichier.',
    constraints: '- Minimum 5 couleurs sémantiques (primary, secondary, success, warning, error)\n- 2 familles typographiques maximum\n- Compatibilité dark mode\n- Toutes les variables nommées selon convention BEM ou similaire',
    criteria: '- Cohérence et logique du système\n- Utilisabilité par une équipe\n- Couverture dark mode\n- Qualité de la documentation',
    specialty: 'UI Designer',
    challenge_type: 'Design System',
    industry: 'SaaS',
    track: 'ux_ui',
    xp_reward: 250,
    deadline_days: 10,
  },
  {
    leagueName: 'Bronze',
    title: 'Brand identity boutique café',
    brief: 'Développe l\'identité visuelle complète d\'un café spécialisé haut de gamme.',
    context: 'Origen est un café de spécialité à Lyon, fondé par un ex-barista champion d\'Europe. Il cible une clientèle CSP+ sensible à l\'authenticité et au storytelling des origines.',
    deliverable: 'Pack identité visuelle : logo principal + variantes, palette couleurs, typographies, moodboard, mockups sur 2 supports (tasse + carte de visite).',
    constraints: '- Ambiance chaleureuse et premium\n- Pas de clichés "café" (grain de café, tasse fumante)\n- Palette de 3 couleurs max\n- Livrables vectoriels',
    criteria: '- Originalité et différenciation\n- Cohérence de l\'identité\n- Qualité des mockups\n- Adéquation avec le positionnement premium',
    specialty: 'Graphic Designer',
    challenge_type: 'Brand Identity',
    industry: 'Food & Beverage',
    track: 'graphic',
    xp_reward: 250,
    deadline_days: 10,
  },
  {
    leagueName: 'Bronze',
    title: 'Wireframes app fitness mobile',
    brief: 'Conçois les wireframes des écrans clés d\'une app mobile de coaching sportif.',
    context: 'FitFlow est une app de coaching fitness qui adapte les entraînements en temps réel selon la fatigue détectée via smartwatch. Elle cible les sportifs amateurs 25-40 ans.',
    deliverable: 'Wireframes basse fidélité des 6 écrans clés : home, session en cours, historique, profil, paramètres, écran post-session. Annotations des interactions principales.',
    constraints: '- Format mobile (375x812px)\n- Basse fidélité uniquement (noir/blanc/gris)\n- Annotations sur chaque interaction non-évidente\n- Pas de contenu réel (lorem ipsum accepté)',
    criteria: '- Couverture des cas d\'usage principaux\n- Cohérence de navigation\n- Clarté des annotations\n- Respect des patterns mobile natifs',
    specialty: 'UX Designer',
    challenge_type: 'Wireframes',
    industry: 'Fitness',
    track: 'ux_ui',
    xp_reward: 250,
    deadline_days: 10,
  },
  {
    leagueName: 'Bronze',
    title: 'Dashboard analytics retail',
    brief: 'Conçois un dashboard de suivi des ventes pour les managers de boutiques retail.',
    context: 'ChainStore est une chaîne de 50 boutiques de mode. Leurs managers passent 2h/jour sur Excel pour suivre leurs KPIs. Ils ont besoin d\'un tableau de bord consolidé en temps réel.',
    deliverable: 'Maquette haute-fidélité du dashboard principal (desktop). Inclure : KPIs clés, graphique de ventes sur 30 jours, top produits, alertes stock.',
    constraints: '- Design desktop first (1440px de large)\n- Max 8 KPIs visibles above the fold\n- Graphiques lisibles sans interaction\n- Utiliser des données fictives cohérentes',
    criteria: '- Densité d\'information optimale\n- Lisibilité des données\n- Priorisation des informations critiques\n- Qualité visuelle',
    specialty: 'UI Designer',
    challenge_type: 'Dashboard',
    industry: 'Retail',
    track: 'ux_ui',
    xp_reward: 250,
    deadline_days: 10,
  },

  // --- SILVER ---
  {
    leagueName: 'Silver',
    title: 'UX Research — onboarding crypto',
    brief: 'Mène une étude UX sur les freins à l\'adoption d\'une app crypto grand public.',
    context: 'CoinEasy veut démocratiser la crypto pour les non-initiés. Leur taux de conversion inscription→premier achat est de 8%. Ils soupçonnent des freins liés à la complexité perçue.',
    deliverable: 'Rapport UX Research : guide d\'entretien (5 questions), synthèse de 5 entretiens simulés (personas), insights clés, 3 recommandations priorisées.',
    constraints: '- Méthodologie entretiens utilisateurs (pas de questionnaire)\n- 5 profils diversifiés (âge, expérience tech)\n- Format PDF ou Figma\n- Insights appuyés par des verbatims',
    criteria: '- Rigueur méthodologique\n- Pertinence des insights\n- Qualité des recommandations\n- Clarté du rapport',
    specialty: 'UX Designer',
    challenge_type: 'UX Research',
    industry: 'Crypto',
    track: 'ux_ui',
    xp_reward: 350,
    deadline_days: 14,
  },
  {
    leagueName: 'Silver',
    title: 'UI Kit composants e-commerce',
    brief: 'Crée un UI kit complet pour une plateforme e-commerce de luxe.',
    context: 'Lumine est une marketplace de produits de luxe multi-marques. Ils refondte leur frontend et ont besoin d\'un UI kit Figma réutilisable par leur équipe de 5 développeurs front-end.',
    deliverable: 'UI Kit Figma avec : boutons (tous états), inputs, cards produit, navigation, footer, badges, modals. Min 30 composants avec variantes et états.',
    constraints: '- Composants Figma avec Auto Layout\n- Variants pour tous les états (default, hover, disabled, error)\n- Respect des standards WCAG AA (contraste)\n- Nommage cohérent des composants',
    criteria: '- Complétude du kit\n- Qualité des variants et états\n- Utilisabilité par les devs (organisation, nommage)\n- Cohérence visuelle premium',
    specialty: 'UI Designer',
    challenge_type: 'UI Kit',
    industry: 'Luxe',
    track: 'ux_ui',
    xp_reward: 350,
    deadline_days: 14,
  },
  {
    leagueName: 'Silver',
    title: 'Social Media Kit agence immobilière',
    brief: 'Conçois un kit de templates réseaux sociaux pour une agence immobilière premium.',
    context: 'Prestige Immo est une agence spécialisée dans les biens d\'exception à Paris. Leur community manager post 4x/semaine mais manque de cohérence visuelle entre les publications.',
    deliverable: '10 templates Canva ou Figma réutilisables : annonce bien, conseil acheteur, statistique marché, témoignage client, coulisse agence. Versions Instagram feed + stories.',
    constraints: '- 10 templates minimum\n- Versions feed (1:1) ET stories (9:16)\n- Cohérence chromatique et typographique\n- Zones de texte et images éditables',
    criteria: '- Cohérence de l\'identité visuelle\n- Diversité des formats\n- Facilité d\'édition\n- Qualité et modernité des templates',
    specialty: 'Graphic Designer',
    challenge_type: 'Social Media Kit',
    industry: 'Immobilier',
    track: 'graphic',
    xp_reward: 350,
    deadline_days: 10,
  },
  {
    leagueName: 'Silver',
    title: 'Prototype app santé connectée',
    brief: 'Crée un prototype interactif pour le suivi de santé d\'une app destinée aux seniors.',
    context: 'SeniorCare est une app de téléassistance médicale pour les 65+. Les aidants peuvent suivre les constantes vitales à distance. L\'app doit être ultra-simple d\'utilisation.',
    deliverable: 'Prototype Figma interactif couvrant le parcours principal : connexion → tableau de bord → détail d\'une constante → alertes. Min 8 écrans liés.',
    constraints: '- Taille de police minimum 18px\n- Zones tactiles minimum 44x44px\n- Contrastes WCAG AAA\n- Pas de jargon médical\n- Interactions smooth (transitions définies)',
    criteria: '- Accessibilité senior\n- Fluidité des interactions\n- Clarté de l\'information médicale\n- Qualité du prototype (pas de liens cassés)',
    specialty: 'UX Designer',
    challenge_type: 'Prototype',
    industry: 'Santé',
    track: 'ux_ui',
    xp_reward: 350,
    deadline_days: 14,
  },

  // --- GOLD ---
  {
    leagueName: 'Gold',
    title: 'Redesign app streaming musical',
    brief: 'Repense l\'expérience d\'écoute d\'une app de streaming musical pour les audiophiles.',
    context: 'Resonance est un concurrent de Tidal qui cible les mélomanes exigeants. Leur app actuelle est perçue comme datée et peu différenciante face à Spotify et Apple Music.',
    deliverable: 'Redesign complet : 10 écrans haute-fidélité (home, recherche, album, player, playlist, profil, paramètres audio, découverte, bibliothèque, équaliseur). Prototype interactif.',
    constraints: '- Ambiance premium et immersive\n- Player audio innovant (pas le player standard)\n- Mode portrait uniquement\n- Accessibilité WCAG AA minimum',
    criteria: '- Innovation du concept player\n- Cohérence de l\'expérience globale\n- Qualité haute-fidélité\n- Différenciation vs concurrents',
    specialty: 'UI Designer',
    challenge_type: 'Redesign',
    industry: 'Musique',
    track: 'ux_ui',
    xp_reward: 500,
    deadline_days: 14,
  },
  {
    leagueName: 'Gold',
    title: 'Packaging produit bien-être premium',
    brief: 'Conçois le packaging d\'une gamme de suppléments bien-être pour une marque D2C premium.',
    context: 'Aurea est une marque de suppléments naturels (magnésium, ashwagandha, oméga-3) lancée par une naturopathe. Elle vend en ligne et en boutiques bio haut de gamme.',
    deliverable: '3 packagings (boîte rectangle 8x8x15cm) pour les 3 produits. Vues dépliées + mockups 3D ou photo-réalistes. Charte graphique packagings.',
    constraints: '- Matériaux eco-responsables à évoquer visuellement\n- Mentions légales fictives incluables\n- Cohérence des 3 packagings avec différenciation par produit\n- Impression offset (pas de dégradés complexes)',
    criteria: '- Impact rayon et lisibilité\n- Cohérence de gamme\n- Qualité des mockups\n- Adéquation positionnement premium + éco',
    specialty: 'Graphic Designer',
    challenge_type: 'Packaging',
    industry: 'Bien-être',
    track: 'graphic',
    xp_reward: 500,
    deadline_days: 14,
  },
  {
    leagueName: 'Gold',
    title: 'UX Case Study app de mobilité',
    brief: 'Documente et présente le processus UX complet d\'une app de mobilité urbaine.',
    context: 'UrbanGo est une app de multimodalité (vélo, trottinette, métro, covoiturage) pour les navetteurs urbains. L\'équipe produit veut un case study pour leur portfolio investisseur.',
    deliverable: 'Case study complet (PDF ou Figma) : problème → recherche → insights → idéation → prototypage → tests → résultats. 15 slides minimum avec visuels.',
    constraints: '- Suivi du processus Double Diamond\n- Inclure des métriques de succès fictives mais cohérentes\n- Visuels pour chaque étape\n- Synthèse exécutive en première page',
    criteria: '- Rigueur du processus UX documenté\n- Qualité narrative et visuelle\n- Cohérence des décisions de design\n- Impact des métriques présentées',
    specialty: 'UX Designer',
    challenge_type: 'UX Case Study',
    industry: 'Mobilité',
    track: 'ux_ui',
    xp_reward: 500,
    deadline_days: 21,
  },
  {
    leagueName: 'Gold',
    title: 'Dark mode app IA cybersécurité',
    brief: 'Crée le dark mode d\'un outil de monitoring cybersécurité pour des équipes SOC.',
    context: 'ShieldOps est un SIEM (Security Information and Event Management) utilisé par des équipes de sécurité 24h/24. Les opérateurs passent 8h/jour devant les dashboards en environnement sombre.',
    deliverable: 'Dark mode complet : 8 écrans (dashboard principal, log explorer, règles d\'alerte, timeline incident, rapport, paramètres, onboarding, profil). Design system dark mode inclus.',
    constraints: '- Fond principal max #1A1A2E\n- Couleurs d\'alerte sémantigues (rouge/orange/jaune/vert)\n- Densité information maximale\n- Accessibilité WCAG AAA pour les éléments critiques',
    criteria: '- Confort visuel sur longue durée\n- Lisibilité des données critiques\n- Cohérence du système dark\n- Innovation dans la visualisation des menaces',
    specialty: 'UI Designer',
    challenge_type: 'Dark Mode',
    industry: 'Cybersécurité',
    track: 'ux_ui',
    xp_reward: 500,
    deadline_days: 14,
  },

  // --- PLATINUM ---
  {
    leagueName: 'Platinum',
    title: 'Design system IA plateforme EdTech',
    brief: 'Crée un design system production-ready pour une plateforme d\'éducation propulsée par l\'IA.',
    context: 'LearnAI est une plateforme d\'apprentissage adaptatif B2B qui génère des parcours pédagogiques par IA pour les entreprises. Leur équipe passe en scale et a besoin d\'un système de design robuste.',
    deliverable: 'Design system Figma complet : fondations (couleurs, typo, spacing, grilles, icônes), composants atomiques (50+), composants composites (20+), patterns de pages, documentation.',
    constraints: '- Architecture Atomic Design\n- Theming multi-marque (light/dark/high contrast)\n- 70+ composants avec variants exhaustifs\n- Documentation inline dans Figma\n- Tokens exportables (JSON)',
    criteria: '- Exhaustivité et cohérence système\n- Scalabilité multi-produit\n- Qualité documentation\n- Accessibilité native des composants',
    specialty: 'UI Designer',
    challenge_type: 'Design System',
    industry: 'Éducation',
    track: 'ux_ui',
    xp_reward: 700,
    deadline_days: 21,
  },
  {
    leagueName: 'Platinum',
    title: 'IA Navigation — super-app sport',
    brief: 'Repense l\'architecture de l\'information d\'une super-app sport intégrant IA et communauté.',
    context: 'SportHub veut fusionner suivi de performances, marketplace équipements, coaching IA et réseau social sportif en une seule app. L\'arborescence actuelle sur 6 niveaux est perçue comme labyrinthique.',
    deliverable: 'Livrable IA/navigation : arbre de contenu annoté, card sorting (résultats simulés), tree testing (résultats simulés), nouvelle IA proposée, maquettes navigation principale (5 écrans).',
    constraints: '- Max 3 niveaux de profondeur\n- Navigation principale max 5 items\n- Basé sur des méthodes UX reconnues (card sorting, tree testing)\n- Inclure les métriques actuelles vs cibles',
    criteria: '- Rigueur de la démarche UX\n- Simplicité de la nouvelle structure\n- Cohérence avec les besoins utilisateurs\n- Qualité des maquettes de navigation',
    specialty: 'UX Designer',
    challenge_type: 'IA / Navigation',
    industry: 'Sport',
    track: 'ux_ui',
    xp_reward: 700,
    deadline_days: 21,
  },
  {
    leagueName: 'Platinum',
    title: 'Identité motion brand crypto',
    brief: 'Crée une identité de marque animée pour un exchange crypto nouvelle génération.',
    context: 'Nexus Exchange cible les traders 20-35 ans qui trouvent les plateformes actuelles trop "corporate". Ils veulent une identité bold, différenciante, avec une forte présence en motion design.',
    deliverable: 'Identité complète : logo animé (5s loop GIF/MP4), intro screen animée (3s), 3 animations d\'interface (loading, confirmation, erreur). + Charte statique complète.',
    constraints: '- Motion design en SVG animé ou After Effects\n- Boucles seamless\n- Durées définies (logo 5s, intro 3s, micro-interactions max 0,4s)\n- Accessible (prefers-reduced-motion pris en compte)',
    criteria: '- Impact et mémorabilité de l\'identité\n- Qualité technique des animations\n- Cohérence motion/statique\n- Respect des timings spec',
    specialty: 'Graphic Designer',
    challenge_type: 'Motion',
    industry: 'Crypto',
    track: 'graphic',
    xp_reward: 700,
    deadline_days: 21,
  },
  {
    leagueName: 'Platinum',
    title: 'Dashboard supply chain temps réel',
    brief: 'Conçois un dashboard de pilotage supply chain pour une chaîne logistique alimentaire mondiale.',
    context: 'FreshChain gère la logistique de 200 produits frais entre 15 pays. Leurs opérateurs ont besoin d\'un dashboard unique pour superviser stocks, transports, alertes rupture et prévisions IA.',
    deliverable: '12 écrans haute-fidélité desktop : dashboard principal, carte mondiale interactive, détail entrepôt, planification transport, alertes, rapport hebdo, comparatif fournisseurs, module prévisions.',
    constraints: '- Desktop 1920px uniquement\n- Données temps réel simulées\n- Visualisations data avancées (treemap, sankey, heat map)\n- Thème sombre obligatoire',
    criteria: '- Densité et lisibilité des données\n- Innovation des visualisations\n- Utilisabilité opérationnelle\n- Qualité du dark theme',
    specialty: 'UI Designer',
    challenge_type: 'Dashboard',
    industry: 'Food & Beverage',
    track: 'ux_ui',
    xp_reward: 700,
    deadline_days: 21,
  },

  // --- DIAMOND ---
  {
    leagueName: 'Diamond',
    title: 'Super-app voyage — expérience bout-en-bout',
    brief: 'Conçois l\'expérience complète d\'une super-app de voyage de bout en bout.',
    context: 'Wandr est une app tout-en-un (inspiration, réservation, itinéraire IA, guide local, communauté) pour les voyageurs indépendants 25-45 ans. Ils lèvent une série A et ont besoin d\'un pitch deck visuel + prototype.',
    deliverable: '20 écrans haute-fidélité + prototype interactif complet couvrant : découverte destination, recherche vols/hôtels, itinéraire IA, guide offline, partage communauté. + Présentation 10 slides du concept.',
    constraints: '- Expérience mobile-first ET tablette\n- Offline mode pour le guide\n- Accessibilité WCAG AA\n- Prototype navigable sans instructions',
    criteria: '- Vision produit cohérente et innovante\n- Qualité et profondeur du prototype\n- Cohérence entre les flux\n- Qualité de la présentation concept',
    specialty: 'UX Designer',
    challenge_type: 'UX Case Study',
    industry: 'Voyage',
    track: 'ux_ui',
    xp_reward: 900,
    deadline_days: 30,
  },
  {
    leagueName: 'Diamond',
    title: 'Design System multi-marque entreprise',
    brief: 'Architecte un design system d\'entreprise gérant 4 marques sous une fondation commune.',
    context: 'MediaGroup possède 4 marques média (news premium, sport, culture, tech). Chaque marque a son identité mais partage infrastructure technique. Ils veulent un design system unique gouvernant les 4.',
    deliverable: 'Design system Figma : couche core (tokens, composants headless), 4 thèmes de marque complets, documentation de gouvernance, guide de contribution, 80+ composants total.',
    constraints: '- Architecture token multi-level (global → brand → component)\n- Chaque marque visuellement distincte mais cohérente au core\n- Documentation de gouvernance (comment contribuer, versioning)\n- Composants core headless (sans style intrinsèque)',
    criteria: '- Architecture et scalabilité du système\n- Qualité de la gouvernance\n- Différenciation des marques dans le système\n- Exhaustivité et maintenabilité',
    specialty: 'UI Designer',
    challenge_type: 'Design System',
    industry: 'Streaming',
    track: 'ux_ui',
    xp_reward: 900,
    deadline_days: 30,
  },
  {
    leagueName: 'Diamond',
    title: 'Brand universe marque luxe — omnicanal',
    brief: 'Développe l\'univers de marque complet d\'une maison de mode de luxe pour tous les canaux.',
    context: 'Velâ est une maison de couture française créée par une styliste reconnue. Elle ouvre sa première boutique flagship à Paris et lance simultanément sa présence digitale. Tout doit être parfait.',
    deliverable: 'Brand bible complète (50+ pages PDF) : logo system, typographies, palette, motifs exclusifs, ton & voix, applications print (packaging, cartes, étiquettes), applications digitales (site, social, email), guidelines photo.',
    constraints: '- Positionnement ultra-premium (Hermès niveau)\n- Cohérence absolue cross-canal\n- Motif signature exclusif\n- Toutes règles d\'utilisation documentées',
    criteria: '- Niveau d\'excellence premium\n- Cohérence cross-canal\n- Originalité des éléments signature\n- Exploitabilité opérationnelle de la brand bible',
    specialty: 'Graphic Designer',
    challenge_type: 'Brand Identity',
    industry: 'Luxe',
    track: 'graphic',
    xp_reward: 900,
    deadline_days: 30,
  },
  {
    leagueName: 'Diamond',
    title: 'Plateforme B2B SaaS — redesign stratégique',
    brief: 'Mène et documente le redesign stratégique complet d\'une plateforme B2B SaaS complexe.',
    context: 'DataBridge est une plateforme d\'intégration de données B2B utilisée par 500 entreprises. NPS à 18. Les équipes produit veulent un redesign guidé par la recherche utilisateur pour passer à NPS 50.',
    deliverable: 'Projet UX complet : research plan, 8 entretiens synthétisés, journey map, prioritisation des problèmes (impact/effort), redesign 15 écrans clés, test usabilité (5 participants simulés), rapport d\'impact.',
    constraints: '- Minimum 3 personas distincts\n- Journey map cross-device\n- Tests usabilité avec protocole documenté\n- Métriques avant/après simulées cohérentes',
    criteria: '- Profondeur et rigueur de la recherche\n- Lien recherche → décisions de design\n- Qualité du redesign\n- Crédibilité des métriques d\'impact',
    specialty: 'UX Designer',
    challenge_type: 'Redesign',
    industry: 'SaaS',
    track: 'ux_ui',
    xp_reward: 900,
    deadline_days: 30,
  },

  // --- MASTER ---
  {
    leagueName: 'Master',
    title: 'Futur de l\'interface bancaire — vision 2030',
    brief: 'Imagine et conçois l\'interface bancaire du futur pour 2030 intégrant IA générative et nouveaux paradigmes.',
    context: 'FutureBank lance un lab d\'innovation pour imaginer l\'expérience bancaire de 2030 intégrant IA conversationnelle, réalité augmentée, interfaces gestuelles et biométrie comportementale.',
    deliverable: 'Vision design 2030 : manifeste (5 pages), 3 concepts d\'interface distincts (5 écrans chacun), prototype interactif du concept principal (15 écrans), présentation investisseurs (15 slides).',
    constraints: '- Cohérence technologique (pas de science fiction pure)\n- Accessibilité maintenue\n- Prise en compte des régulations bancaires\n- 3 concepts vraiment différenciés',
    criteria: '- Pertinence et crédibilité de la vision\n- Qualité des 3 concepts\n- Profondeur du prototype principal\n- Impact de la présentation',
    specialty: 'UX Designer',
    challenge_type: 'Prototype',
    industry: 'Fintech',
    track: 'ux_ui',
    xp_reward: 1200,
    deadline_days: 30,
  },
  {
    leagueName: 'Master',
    title: 'Identité de marque pays — tourisme',
    brief: 'Crée l\'identité de marque nationale d\'un pays pour attirer les touristes et les investisseurs.',
    context: 'Le Ministère du Tourisme d\'un pays fictif (Aelvara, pays méditerranéen de 5M d\'habitants) lance un appel d\'offres pour refondre son image de marque internationale après une crise de réputation.',
    deliverable: 'Identité nationale complète : stratégie de marque, logo et système d\'identité, campagne internationale (affiche, digital, vidéo de 30s storyboard), guide d\'application pour 50 cas d\'usage.',
    constraints: '- Respecter la culture et l\'histoire du pays fictif (à construire)\n- Applicable par des partenaires tiers\n- Version anglaise + 3 autres langues au choix\n- Aucun stéréotype réducteur',
    criteria: '- Profondeur de la stratégie de marque\n- Système d\'identité robuste et flexible\n- Qualité et impact de la campagne\n- Exhaustivité des cas d\'usage',
    specialty: 'Graphic Designer',
    challenge_type: 'Brand Identity',
    industry: 'Voyage',
    track: 'graphic',
    xp_reward: 1200,
    deadline_days: 30,
  },
  {
    leagueName: 'Master',
    title: 'Plateforme IA santé — éthique et expérience',
    brief: 'Conçois une plateforme de diagnostic IA médicale en intégrant les enjeux éthiques au cœur du design.',
    context: 'MedAI est une startup développant un outil d\'aide au diagnostic par IA pour les médecins généralistes. Les enjeux éthiques (biais algorithmiques, consentement, explainabilité) doivent être intégrés dans l\'UX.',
    deliverable: 'Système de design éthique : framework éthique UX (document), 20 écrans haute-fidélité couvrant tous les cas d\'usage, prototype interactif, rapport d\'audit éthique du design proposé.',
    constraints: '- Explainabilité de l\'IA visible dans l\'interface\n- Consentement éclairé patient intégré dans les flux\n- Conformité RGPD dans les patterns d\'interface\n- Tests d\'accessibilité documentés',
    criteria: '- Intégration réelle de l\'éthique dans l\'UX (pas cosmétique)\n- Qualité du système de design\n- Profondeur du prototype\n- Pertinence du rapport d\'audit éthique',
    specialty: 'UX Designer',
    challenge_type: 'UX Case Study',
    industry: 'Santé',
    track: 'ux_ui',
    xp_reward: 1200,
    deadline_days: 30,
  },
  {
    leagueName: 'Master',
    title: 'Design system open-source gouvernance',
    brief: 'Crée un design system open-source complet avec sa gouvernance communautaire.',
    context: 'OpenDesign Foundation veut lancer un design system communautaire pour les ONG mondiales. Le système doit être accessible, multilingue, adaptable culturellement, et maintenu par une communauté distribuée.',
    deliverable: 'Design system open-source : 100+ composants Figma, tokens exportables (CSS, JSON, Swift, Kotlin), documentation site statique (contenu complet), guide de contribution, roadmap publique, kit de démarrage 5 langues.',
    constraints: '- WCAG AAA pour tous les composants\n- Support RTL (arabe, hébreu)\n- Tokens nommés selon W3C Design Token format\n- Licence permissive (MIT ou Apache 2.0)\n- Versioning sémantique',
    criteria: '- Exhaustivité et qualité technique du système\n- Accessibilité réelle (pas seulement déclarée)\n- Qualité de la documentation et gouvernance\n- Scalabilité communautaire',
    specialty: 'UI Designer',
    challenge_type: 'Design System',
    industry: 'ONG',
    track: 'ux_ui',
    xp_reward: 1200,
    deadline_days: 30,
  },

  // --- LEGEND ---
  {
    leagueName: 'Legend',
    title: 'Redesign OS mobile — paradigme IA-first',
    brief: 'Imagine le redesign complet d\'un système d\'exploitation mobile centré sur l\'IA générative.',
    context: 'NextOS est un projet de recherche visant à reimaginer l\'OS mobile pour un monde IA-first. L\'objectif est de challenger les paradigmes établis par iOS et Android en repensant fondamentalement les interactions.',
    deliverable: 'Vision système complète : manifeste UX (10 pages), nouveau langage d\'interaction documenté, 30 écrans haute-fidélité couvrant home, navigation, notifications, IA assistant intégré, apps natives repensées, prototype interactif avancé.',
    constraints: '- Cohérence technologique plausible en 2028\n- Système d\'interaction cohérent (pas un patchwork d\'idées)\n- Accessibilité first-class\n- Documentation des décisions de design',
    criteria: '- Audace et cohérence de la vision\n- Qualité et profondeur du système\n- Innovation réelle (pas que cosmétique)\n- Prototype et présentation de niveau world-class',
    specialty: 'UX Designer',
    challenge_type: 'Redesign',
    industry: 'IA',
    track: 'ux_ui',
    xp_reward: 1500,
    deadline_days: 45,
  },
  {
    leagueName: 'Legend',
    title: 'Univers de marque gaming — lancement mondial',
    brief: 'Crée l\'univers visuel complet pour le lancement mondial d\'un jeu AAA.',
    context: 'Nexus Games lance Axiom, un RPG open-world en 2026. L\'univers se déroule dans une mégapole cyberpunk-fantasy. Ils ont besoin d\'une identité visuelle qui rivalise avec les plus grandes franchises mondiales.',
    deliverable: 'Brand universe complet : lore visuel (worldbuilding graphique), identité de marque (logo, typographie exclusive, couleurs signature), campagne de lancement (20 visuels, 3 formats pub, teaser storyboard 60s), design de l\'interface in-game (HUD, menus, inventaire).',
    constraints: '- Cohérence entre univers in-game et marketing\n- Identité reconnaissable en 1 seconde\n- Adaptée au marché mondial (pas de symboles culturellement problématiques)\n- Visuels adaptés aux réseaux majeurs (YouTube, Twitch, TikTok, X)',
    criteria: '- Puissance et cohérence de l\'univers visuel\n- Qualité cinématographique des visuels\n- Cohérence brand/in-game\n- Potentiel viral et mémorabilité',
    specialty: 'Graphic Designer',
    challenge_type: 'Brand Identity',
    industry: 'Gaming',
    track: 'graphic',
    xp_reward: 1500,
    deadline_days: 45,
  },
  {
    leagueName: 'Legend',
    title: 'Écosystème produit IA — vision stratégique',
    brief: 'Conçois la vision UX stratégique d\'un écosystème de produits IA pour une entreprise Fortune 500.',
    context: 'GlobalCorp (Fortune 500, 80 000 employés) veut transformer tous ses outils internes avec l\'IA générative. 15 outils existants, 8 nouvelles apps prévues, 12 équipes produit. Vous êtes le design lead stratégique.',
    deliverable: 'Vision stratégique UX : audit de l\'existant (synthèse), vision système 3 ans, design principles IA, architecture produit (comment les 23 produits s\'articulent), design system d\'entreprise, roadmap design 18 mois, 3 prototypes des initiatives phares.',
    constraints: '- Faisabilité organisationnelle (pas seulement technique)\n- Plan de transition progressif\n- Gouvernance design documentée\n- Métriques de succès pour chaque initiative',
    criteria: '- Pertinence stratégique de la vision\n- Cohérence de l\'architecture système\n- Réalisme de la roadmap\n- Qualité des prototypes phares',
    specialty: 'UX Designer',
    challenge_type: 'UX Case Study',
    industry: 'IA',
    track: 'ux_ui',
    xp_reward: 1500,
    deadline_days: 45,
  },
  {
    leagueName: 'Legend',
    title: 'Design system génératif — IA-driven',
    brief: 'Crée un design system dont les composants s\'adaptent dynamiquement via IA.',
    context: 'AdaptUI est une startup qui veut révolutionner les design systems en permettant aux composants de s\'adapter visuellement selon le contexte utilisateur, la marque et l\'accessibilité, pilotés par un LLM.',
    deliverable: 'Design system génératif : architecture système (documentation technique), 50+ composants avec logique d\'adaptation documentée (règles IA), démonstration sur 3 thèmes automatiquement générés, guide d\'intégration LLM, prototype interactif montrant l\'adaptation en temps réel.',
    constraints: '- Architecture token-driven obligatoire\n- Les règles d\'adaptation doivent être explicites et documentées (pas de boîte noire)\n- Compatibilité avec les outils standard (Figma, Storybook, Tailwind)\n- WCAG AA maintenu sur tous les thèmes générés',
    criteria: '- Innovation conceptuelle réelle\n- Qualité de l\'architecture\n- Clarté de la documentation des règles\n- Qualité du prototype de démonstration',
    specialty: 'UI Designer',
    challenge_type: 'Design System',
    industry: 'IA',
    track: 'ux_ui',
    xp_reward: 1500,
    deadline_days: 45,
  },
]

async function main() {
  console.log('Fetching leagues...')
  const { data: leagues, error: leagueErr } = await (supabase as any)
    .from('leagues')
    .select('id, name')

  if (leagueErr) {
    console.error('Failed to fetch leagues:', leagueErr.message)
    process.exit(1)
  }

  const leagueMap: Record<string, string> = {}
  for (const l of leagues) {
    leagueMap[l.name] = l.id
  }

  console.log('Available leagues:', Object.keys(leagueMap).join(', '))

  const toInsert = challenges.map(c => {
    const league_id = leagueMap[c.leagueName]
    if (!league_id) {
      console.warn(`No league found for "${c.leagueName}"`)
    }
    return {
      title: c.title,
      brief: c.brief,
      context: c.context,
      deliverable: c.deliverable,
      constraints: c.constraints,
      criteria: c.criteria,
      specialty: c.specialty,
      challenge_type: c.challenge_type,
      industry: c.industry,
      track: c.track,
      xp_reward: c.xp_reward,
      deadline_days: c.deadline_days,
      league_id: league_id ?? null,
      level: 'rookie',
      is_published: true,
      month: new Date().getMonth() + 1,
      year: new Date().getFullYear(),
      reveal_at: new Date().toISOString(),
      closes_at: new Date(Date.now() + 365 * 86400000).toISOString(),
      status: 'active',
    }
  })

  console.log(`Inserting ${toInsert.length} challenges...`)
  const { data, error } = await (supabase as any)
    .from('challenges')
    .insert(toInsert)
    .select('id, title')

  if (error) {
    console.error('Insert error:', error.message)
    process.exit(1)
  }

  console.log(`✓ Inserted ${data.length} challenges:`)
  for (const c of data) {
    console.log(` - ${c.title} (${c.id})`)
  }
}

main()
